homework/config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :locations do
    resources :courses do
      resources :students
    end
  end

end

homework/app/models/course.rb
class Course < ActiveRecord::Base
  
  has_many :students
  has_many :join_tables
  has_many :locations, through: :join_tables

end

homework/app/models/join_table.rb
class JoinTable < ActiveRecord::Base
  belongs_to :course
  belongs_to :location
end

homework/app/models/location.rb
class Location < ActiveRecord::Base
  has_many :students
  has_many :join_tables
  has_many :courses, through: :join_tables

end  

homework/app/models/student.rb
class Student < ActiveRecord::Base
  belongs_to :location
  belongs_to :course
end

homework/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

homework/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_filter :find_location
  before_filter :find_course, only:[:show, :edit, :update, :destroy]

  def new
    @course = Course.new
  end

  def create
    @course = @location.courses.create course_params
    redirect_to location_path(@location)
  end

  def show
    @student = @course.students
    #custom query
  end

  def edit
  end

  def update
  end

  def destroy
  end

   private
   def find_location
      @location = Location.find params[:location_id]
   end
   def course_params
      params.require(:course).permit(:name)
   end
   def find_course
      @course = @location.courses.find params[:id]
   end
   
end

homework/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @locations = Location.all
  end
end

homework/app/controllers/locations_controller.rb
class LocationsController < ApplicationController

   before_filter :find_location, only:[:show, :edit, :update, :destroy]

  def new
    @course = Course.all
    @locations = Location.new
  end

  def create

    @locations = Location.create location_params
    redirect_to root_path
  end

  def show
    @courses = @locations.courses
  end

  def edit
    @course = @locations.courses
  end

  def update
  end

  def destroy
  end

   private

   def  location_params
      params.require(:location).permit(:name, {course_ids: []})
   end
   def find_location
      @locations = Location.find params[:id]
   end

end

homework/app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_filter :find_location
  before_filter :find_course
  before_filter :find_student, only:[:show, :edit, :update, :destroy]
  
  def new
    @student = Student.new
  end

  def create
    @student = @course.students.create student_params
    redirect_to location_course_path(@location, @course)
  end

  def show
    # @student = @course.students
  end

  def edit
    # @student = @course.student
  end

  def update
    @student.update_attributes student_params
    redirect_to location_course_path(@location, @course)
  end

  def destroy
  end

   private
    def student_params
      params.require(:student).permit(:name,
        :email,
        :phone,
        :bio,
        :social_1,
        :social_2,
        :social_3,
        :location_id)
    end

    def find_location
      @location = Location.find params[:location_id]
    end
   
    def find_course
      @course = Course.find params[:course_id]
    end

    def find_student
      @student = Student.find params[:id]
    end
end

homework/app/helpers/application_helper.rb
module ApplicationHelper
end

homework/app/helpers/courses_helper.rb
module CoursesHelper
end

homework/app/helpers/home_helper.rb
module HomeHelper
end

homework/app/helpers/locations_helper.rb
module LocationsHelper
end

homework/app/helpers/students_helper.rb
module StudentsHelper
end

homework/app/views/courses/_form.html.haml
= form_for [@location, @course] do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

  %br
= link_to "Cancel", location_path(@location)

%p
= link_to "Return to Home Page", root_path

homework/app/views/courses/new.html.haml
%h3 Course
=render 'form'

homework/app/views/courses/show.html.haml
%h3 #{@location.name} #{@course.name} Students
%br
= link_to "Add Student", new_location_course_student_path(@location, @course)
%hr
-@student.each do |student|
    %br
    =link_to student.name, location_course_student_path(@location, @course, student)
    |
    =link_to "edit", edit_location_course_student_path(@location, @course, student)

%br
%hr
%br
= link_to "Go Back To #{@location.name} Courses", location_path(@location)

homework/app/views/home/index.html.haml
%h3 Iron Yard Locations
=link_to "New Location", new_location_path
%hr
- @locations.each do |location|
  %br
  = link_to location.name, location_path(location)
  |
  = link_to "Edit", edit_location_path(location)

homework/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>The Ironbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Chewy' rel='stylesheet' type='text/css'>
</head>
<body>

    <div class="container">
      <div class="header">
        <form class="navbar-form navbar-right">
          <p></p>
        </form>
      </div>

      <div class="jumbotron">
        <h1>The Ironbook</h1>

      <%= yield %>

      </div>

      <div class="footer">
        <p>&copy; <a href="/">Team Awesome 2014</a></p>
      </div>

    </div>
  </body>
</html>

homework/app/views/locations/_form.html.haml
= form_for @locations do |f|
  = f.label :name
  = f.text_field :name
  = f.submit
  %p
  - @course.each do |course|
    = check_box_tag 'location[course_ids][]', course.id, false, {id: "course_id_#{course.id}"}
    = label_tag "course_id_#{course.id}", course.name
    %br

%p
= link_to "Return to Home Page", root_path

homework/app/views/locations/edit.html.haml
%h3 Edit Location

= form_for @locations do |f|
  = f.label :name
  = f.text_field :name
  = f.submit
  %br
  - @course.each do |course|
    = check_box_tag 'location[course_ids][]', course.id, @course.include?(course), {id: "course_id_#{course.id}"}
    = label_tag "course_id_#{course.id}", course.name
=link_to "cancel", root_path

homework/app/views/locations/new.html.haml
%h3 Create New Location

= render 'form'

homework/app/views/locations/show.html.haml
%h3 #{@locations.name} Iron Yard
= link_to "Add Course", new_location_course_path(@locations)

%br
%hr
 
  -@courses.each do |course|
    %br
    =link_to course.name, location_course_path(@locations, course)
%br
%hr

%p
= link_to "Return to Home Page", root_path

homework/app/views/students/_form.html.haml
= form_for [@location, @course, @student] do |f|
  = f.hidden_field :location_id, value: @location.id
  = f.label :name
  = f.text_field :name
  %br
  = f.label :email
  = f.text_field :email
  %br
  = f.label :phone
  = f.text_field :phone
  %br
  = f.label :bio
  = f.text_field :bio
  %br
  = f.label :social_1
  = f.text_field :social_1
  %br
  = f.label :social_2
  = f.text_field :social_2
  %br
  = f.label :social_3
  = f.text_field :social_3
  %br
  = f.submit
<<<<<<< HEAD
= link_to "Cancel", location_course_path(@location, @course)
=======

%p
= link_to "Return to Home Page", root_path
>>>>>>> upstream/master

homework/app/views/students/edit.html.haml
= render 'form'

homework/app/views/students/new.html.haml
%h3 Student Info

=render 'form'

homework/app/views/students/show.html.haml
%h3 #{@student.name}'s Info

/ -@student.each do |student|
/     %br
=@student.name
%br
=@student.phone
%br
=@student.bio
%br
=@student.social_1
%br
=@student.social_2
%br
=@student.social_3
%br
%hr
=link_to "List of Students", location_course_path(@location, @course)